//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CENAODB.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarCityDBEntities : DbContext
    {
        public CarCityDBEntities()
            : base("name=CarCityDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<colores> colores { get; set; }
        public virtual DbSet<IngresoOrden> IngresoOrden { get; set; }
        public virtual DbSet<tipoMecanica> tipoMecanica { get; set; }
        public virtual DbSet<Mecanico> Mecanico { get; set; }
    }
}
