//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CENAODB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoOrden
    {
        public int ordenId { get; set; }
        public int clienteId { get; set; }
        public int mecanicaId { get; set; }
        public int colorId { get; set; }
        public string marca { get; set; }
        public string anio { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string Estado { get; set; }
        public string diagnostico { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<int> usuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
        public Nullable<int> usuarioModifica { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual colores colores { get; set; }
        public virtual tipoMecanica tipoMecanica { get; set; }
    }
}
